import datetime
import streamlit as st
import requests
import sys
import os
from utils.save_to_document import save_document

Base_URL = "http://localhost:8000"

st.set_page_config(
    page_title = "🌍 Travel Planner Agentic Application",
    page_icon = "🌍" ,
    layout="centered",
    initial_sidebar_state = "expanded"
)

st.title(" Travel Planner Agentic Application")

if "messages" not in st.session_state:
    st.session_state .messages = []

st.header("How can I help you in planning a trip? Let me know where do you want to visit?")

with st.form(key="query_form", clear_on_submit = True):
    user_input = st.text_input("User Input", placeholder = "e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("send")
    
 
if submit_button and user_input.strip():
    try:
        with st.spinner("Bot is thinking"):
            payload = {"question": user_input}
            response = requests.post(f"{Base_URL}/query", json=payload)
        
        if response.status_code ==200:
            answer = response.json().get("answer","No answer returned")
            markdown_content = f"""# AI Travel Plan
            
            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}
            # **Created by:** SJ Travel Agent
            ---
            
            {answer}
            
            ---
            
            *This travel plan was generated by AI. Please verify all the information, prices, operating hours*
            """
            st.markdown(markdown_content)
            # Save document locally and offer download
            try:
                saved_path = save_document(answer, directory="./output")
                if saved_path and os.path.exists(saved_path):
                    with open(saved_path, "rb") as f:
                        st.download_button(
                            label="Download travel plan (Markdown)",
                            data=f,
                            file_name=os.path.basename(saved_path),
                            mime="text/markdown"
                        )
                else:
                    st.warning("Could not save the travel plan file.")
            except Exception as e:
                st.error(f"Error saving or offering download: {e}")
                # Try to create a PDF version as well
                try:
                    pdf_path = save_document(answer, directory="./output")
                    # If save_document returned a path, construct PDF filename
                    if pdf_path:
                        # call save_document_pdf which returns the pdf path
                        from utils.save_to_document import save_document_pdf
                        generated_pdf = save_document_pdf(answer, directory="./output")
                        if generated_pdf and os.path.exists(generated_pdf):
                            with open(generated_pdf, "rb") as pf:
                                st.download_button(
                                    label="Download travel plan (PDF)",
                                    data=pf,
                                    file_name=os.path.basename(generated_pdf),
                                    mime="application/pdf"
                                )
                        else:
                            st.info("PDF generation not available (install 'weasyprint' or 'reportlab').")
                except Exception as e:
                    st.error(f"Error generating PDF: {e}")
            
        else:
            st.error("Bot failed to respond:" +  response.text)
            
    except Exception as e:
        st.error(f"The response failed due to {e}")