import os
import datetime
from typing import Optional

def save_document(response_text: str, directory:str = "./output"):
    """ Export travel plan to markdown file with proper formatting"""
    os.makedirs(directory, exist_ok = True)
    
    
    markdown_content = f""" # Travel Plan
    # ** Generated: ** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}
    # created by: ** SJ Travel Agent **
    ---
    {response_text}
    
    ---
    
    * This document was generated by SJ Travel Agent, your personal travel planning assistant. *
    
    """
    try: 
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{directory}/AI_Travel_Plan_{timestamp}.md"
        
        print(filename)
        
        with open(filename, "w", encoding="utf-8") as f:
            f.write(markdown_content)
        
        print(f"Travel plan saved to {filename}")
        return filename
    except Exception as e:
        print(f"Error saving travel plan: {e}")
        return None 


def save_document_pdf(response_text: str, directory: str = "./output", pdf_filename: Optional[str] = None) -> Optional[str]:
    """Save the response text as a PDF.

    This function first converts the markdown text to HTML (if markdown package
    is available) then tries to render to PDF using WeasyPrint. If WeasyPrint
    is not available it falls back to a simple text-based PDF using ReportLab.

    Returns the PDF file path on success, or None on failure.
    """
    os.makedirs(directory, exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    if not pdf_filename:
        pdf_filename = f"AI_Travel_Plan_{timestamp}.pdf"
    pdf_path = os.path.join(directory, pdf_filename)

    # Try WeasyPrint first (best HTML->PDF quality)
    try:
        try:
            import markdown as md
        except Exception:
            md = None

        try:
            from weasyprint import HTML
            weasy_available = True
        except Exception:
            weasy_available = False

        if weasy_available:
            html_text = md.markdown(response_text) if md is not None else f"<pre>{response_text}</pre>"
            HTML(string=html_text).write_pdf(pdf_path)
            print(f"PDF saved to {pdf_path} using WeasyPrint")
            return pdf_path

        # Fallback: use ReportLab to write a simple text PDF
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.pdfgen import canvas
        except Exception as e:
            print("Neither WeasyPrint nor ReportLab are available. Install 'weasyprint' or 'reportlab' to enable PDF export.")
            return None

        # Create a simple PDF with line-wrapped text
        c = canvas.Canvas(pdf_path, pagesize=letter)
        width, height = letter
        margin = 40
        y = height - margin
        max_width = width - margin * 2
        # simple wrap: split by lines and wrap long lines by characters
        lines = response_text.splitlines()
        for line in lines:
            # naive wrap at ~90 chars
            while len(line) > 0:
                chunk = line[:90]
                c.drawString(margin, y, chunk)
                line = line[90:]
                y -= 12
                if y < margin:
                    c.showPage()
                    y = height - margin
        c.save()
        print(f"PDF saved to {pdf_path} using ReportLab fallback")
        return pdf_path

    except Exception as e:
        print(f"Error creating PDF: {e}")
        return None
        